name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # Install your package in development mode
        pip install -e .
        
    - name: Debug info
      run: |
        python -c "import sys; print(sys.executable)"
        python -c "import sys; print(sys.path)"
        pip list
        
    - name: Run tests
      run: |
        # Set PYTHONPATH to include the project root
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest
